### ISSUE TITLE
Unable to install 'fullpath', 'isstring' and 'touch' from pypi 

### ISSUE THREAD

**Issue by bboerner** [russianidiot/fullpath.py#1]
Some packages updated on pypi on Aug 5 2016 cannot be installed due to requirement 're' not on pypi.

Packages I've been unable to install are 'fullpath', 'isstring', and 'touch' (depends on fullpath).

What's odd is fullpath version.txt is 0.0.10 but the version on pypi is 0.0.11.

```
$ pip install --user -U fullpath
Collecting fullpath
  Using cached fullpath-0.0.11.tar.gz
Collecting re (from fullpath)
  Could not find a version that satisfies the requirement re (from fullpath) (from versions: )
No matching distribution found for re (from fullpath)

$ pip install --user -U isstring
Collecting isstring
  Using cached isstring-0.0.11.tar.gz
Collecting re (from isstring)
  Could not find a version that satisfies the requirement re (from isstring) (from versions: )
No matching distribution found for re (from isstring)
```

**Comment by bboerner** [comment]
I see the packages where updated on Aug 12th but still have dependency problems:

```
wbtimber@atx1:~/tmp$ pip install --user -U isstring
Collecting isstring
  Downloading isstring-0.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8slKS2/isstring/setup.py", line 2, in <module>
        from setupfiles import setup
    ImportError: No module named setupfiles
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8slKS2/isstring/
wbtimber@atx1:~/tmp$ pip install --user -U touch
Collecting touch
  Downloading touch-0.0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kqUkZ_/touch/setup.py", line 2, in <module>
        from setupfiles import setup
    ImportError: No module named setupfiles
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kqUkZ_/touch/
wbtimber@atx1:~/tmp$ pip install --user -U fullpath
Collecting fullpath
  Downloading fullpath-0.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-FvQQBg/fullpath/setup.py", line 2, in <module>
        from setupfiles import setup
    ImportError: No module named setupfiles
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FvQQBg/fullpath/
```
Manually installing setupfiles is broken due to https://github.com/russianidiot/setupfiles.py/issues/1.

**Comment by bboerner** [comment]
Thanks for the fixes on 8/21 and 8/22.
